### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ERROR0cai** [RyensX/MediaBox#107]
进入“浏览”界面时全白，提示这个
A migration from 1 to 2 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migratio
n ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructive
Migration* methods.

**Comment by RyensX** [comment]
数据库升级问题。晚点我修一下

**Comment by ERROR0cai** [comment]
> 数据库升级问题。晚点我修一下

哈哈哈，我清除数据倒是又可以了，只是收藏的都没了，不过还是谢谢啦，也是麻烦你了作者😂

**Comment by RyensX** [comment]
> > 数据库升级问题。晚点我修一下
> 
> 哈哈哈，我清除数据倒是又可以了，只是收藏的都没了，不过还是谢谢啦，也是麻烦你了作者😂

抱歉😂另外收藏记录WebDAV备份也很快加上

**Comment by RyensX** [comment]
可以升级一下2.61试试
