### ISSUE TITLE
关于音画不同步问题

### ISSUE THREAD

**Issue by Extrwave** [RyensX/MediaBox#43]
出现在樱花动漫的两个插件中，播放半分钟左右后会出现画面暂停声音继续导致音画不同步问题，复现率很高，望开发者检查一下

**Comment by Extrwave** [comment]
其他插件没有测试，估计是项目本体的问题

**Comment by RyensX** [comment]
> 其他插件没有测试，估计是项目本体的问题

大概是解码器问题，但也和手机的硬件和系统有关，不然我不可能发现不了这么明显的问题。

麻烦报一下系统、具体播放的资源

**Comment by Extrwave** [comment]
确实，应该是解码器问题我刚在浏览器也遇到了。realme x7 pro 3.0的安卓12系统，资源是《异世界迷宫后宫》，貌似所有资源都会，解码器问题

**Comment by Extrwave** [comment]
不知道如何解决

**Comment by RyensX** [comment]
> 确实，应该是解码器问题我刚在浏览器也遇到了。realme x7 pro 3.0的安卓12系统，资源是《异世界迷宫后宫》，貌似所有资源都会，解码器问题

你可以设置里切换内核试试
