### ISSUE TITLE
左右滑动的灵敏度是否需要调低点？

### ISSUE THREAD

**Issue by TwooSix** [RyensX/MediaBox#46]
侧躺着用拇指上下滑的时候，非常容易被判定为左右滑动

**Comment by RyensX** [comment]
具体是怎么滑的？我没觉得容易误触

**Comment by TwooSix** [comment]
> 具体是怎么滑的？我没觉得容易误触

大约是30°-45°之间的斜滑？可以横向对比一下B站首页在斜滑的时候对左右滑的判定，B站要宽容许多

**Comment by RyensX** [comment]
> > 具体是怎么滑的？我没觉得容易误触
> 
> 大约是30°-45°之间的斜滑？可以横向对比一下B站首页在斜滑的时候对左右滑的判定，B站要宽容许多

设计上低于45当然判断为横向

**Comment by TwooSix** [comment]
> > > 具体是怎么滑的？我没觉得容易误触
> > 
> > 
> > 大约是30°-45°之间的斜滑？可以横向对比一下B站首页在斜滑的时候对左右滑的判定，B站要宽容许多
> 
> 设计上低于45当然判断为横向

可能是我表达有误，我是表达的和纵向之间的夹角

**Comment by RyensX** [comment]
> > > > 具体是怎么滑的？我没觉得容易误触
> > > 
> > > 
> > > 大约是30°-45°之间的斜滑？可以横向对比一下B站首页在斜滑的时候对左右滑的判定，B站要宽容许多
> > 
> > 
> > 设计上低于45当然判断为横向
> 
> 可能是我表达有误，我是表达的和纵向之间的夹角

我试了一下纵向35似乎并没有误触

**Comment by TwooSix** [comment]
> > > > > 具体是怎么滑的？我没觉得容易误触
> > > > 
> > > > 
> > > > 大约是30°-45°之间的斜滑？可以横向对比一下B站首页在斜滑的时候对左右滑的判定，B站要宽容许多
> > > 
> > > 
> > > 设计上低于45当然判断为横向
> > 
> > 
> > 可能是我表达有误，我是表达的和纵向之间的夹角
> 
> 我试了一下纵向35似乎并没有误触

能否提供一个邮箱？我可以发送一个录屏附件作为我操作的参考

**Comment by RyensX** [comment]
> > > > > > 具体是怎么滑的？我没觉得容易误触
> > > > > 
> > > > > 
> > > > > 大约是30°-45°之间的斜滑？可以横向对比一下B站首页在斜滑的时候对左右滑的判定，B站要宽容许多
> > > > 
> > > > 
> > > > 设计上低于45当然判断为横向
> > > 
> > > 
> > > 可能是我表达有误，我是表达的和纵向之间的夹角
> > 
> > 
> > 我试了一下纵向35似乎并没有误触
> 
> 能否提供一个邮箱？我可以发送一个录屏附件作为我操作的参考

你可以加群，APP里有链接
