### ISSUE TITLE
换集导致进度条不正确bug反馈

### ISSUE THREAD

**Issue by LL654321** [RyensX/MediaBox#48]
bug描述：假设视频第一集看到片尾（我不想看片尾），直接切换第二集的时候，第二集进度条会定位到片尾，而不是片头。

环境是：Android 12
OPPO find x2pro

**Comment by RyensX** [comment]
已知bug，试试最新版樱花2插件，已经尝试修复了

**Comment by RyensX** [comment]
另外，最新版APP已经默认关闭自动跳转

**Comment by LL654321** [comment]
刚刚更新了之后已无该bug，谢谢大佬回复

**Comment by RyensX** [comment]
> 刚刚更新了之后已无该bug，谢谢大佬回复

感谢反馈:)
