### ISSUE TITLE
关于debug版本

### ISSUE THREAD

**Issue by MaybeQHL** [RyensX/MediaBox#50]
是否可以进行覆盖安装，保留原来的数据。

**Comment by RyensX** [comment]
当然可以覆盖安装

**Comment by MaybeQHL** [comment]
嗯嗯，我安装错了 降级导致数据不能覆盖。

**Comment by RyensX** [comment]
> 嗯嗯，我安装错了 降级导致数据不能覆盖。 

一个测试版通常在下一个release前不会更新版本号，所以其实也可以降级

**Comment by MaybeQHL** [comment]
![3a2d8aa66f464d7020dd2845c73952a](https://user-images.githubusercontent.com/34638673/184835145-097fd719-f70b-4abd-979a-ef459c173e7c.jpg)
这个是正常吗？虽然一般不会降级

**Comment by RyensX** [comment]
> ![3a2d8aa66f464d7020dd2845c73952a](https://user-images.githubusercontent.com/34638673/184835145-097fd719-f70b-4abd-979a-ef459c173e7c.jpg)
> 这个是正常吗？虽然一般不会降级

这样当然不能降级，测试版只有在一个release版本内版本号是不会变的

**Comment by MaybeQHL** [comment]
嗯嗯 好的。

**Comment by MaybeQHL** [comment]
那升级的话，跨版本数据也会清空吗

**Comment by RyensX** [comment]
> 那升级的话，跨版本数据也会清空吗

不会啊，无法降级安装只是系统的限制

**Comment by MaybeQHL** [comment]
> 不会啊，无法降级安装只是系统的限制

好的。
