### ISSUE TITLE
应用的插件仓库页不受控制疯狂更新

### ISSUE THREAD

**Issue by smarttommyau** [RyensX/MediaBox#64]
切换至这个页面后就出现这个情况。

https://user-images.githubusercontent.com/75346987/201462497-b4dec371-8481-4e54-a9e6-933abe07f422.mp4

**Comment by RyensX** [comment]
已知bug，我会排查一下。你现在是随便打开都会这样吗

**Comment by smarttommyau** [comment]
只是偶尔出现

**Comment by RyensX** [comment]
> 只是偶尔出现

有什么具体操作可以复现吗？

**Comment by smarttommyau** [comment]
https://user-images.githubusercontent.com/75346987/202320739-70917f66-95ea-4d7b-86ce-8cfa2296397d.mp4

**Comment by RyensX** [comment]
> 

我按照视频做法也依然无法复现，你的是什么设备什么系统，华为？

**Comment by RyensX** [comment]
> 华为平板 matepad10.4 2021年出的版本。harmonyos2 大概是android 10的内核

你试试最新的测试版，如果还是存在问题就抓一下复现时的log发我看一下

**Comment by smarttommyau** [comment]
要下载两个插件以上才能触发。还有新的bug，现在在多次卡bug就变成下图的情况，下载了的插件在主页不显示，还不断弹下图的弹窗
![Screenshot_20221118_125656_com su mediabox debug](https://user-images.githubusercontent.com/75346987/202620324-ea6d55e6-4e82-4529-84a3-ebfdd7ced384.jpg)

**Comment by smarttommyau** [comment]
经过无数次重进主页就回复正常能显示插件，弹窗也消停了，旧bug仍然能刷出，

**Comment by smarttommyau** [comment]
上边的弹窗，在旧bug发生中的时候，把插件卸载，也能产生，但具有偶然性，不是经常能卡出

**Comment by RyensX** [comment]
虽然如此，但我的设备上依然无法复现。插件列表的更新依赖于插件文件目录和包变更通知，你可以把log发我分析一下

**Comment by smarttommyau** [comment]
```
2756   │ 11-19 10:37:37.015 23040 25756 E ziparchive: Zip: failed to read at offset 0
2757   │ 11-19 10:37:37.015 23040 25756 E ziparchive: Zip: read 3488 from offset 0 failed
2758   │ 11-19 10:37:37.015 23040 25756 E .mediabox.debu: Failed to open APK '/storage/emulated/0/Android/data/com.su.mediabox.debug/files/plugins/oat' I/O error
```
感觉这几行也挺可疑的

**Comment by RyensX** [comment]
粗略看了一下，可能是这里系统在不断生成优化
![IMG_20221119_105621.jpg](https://user-images.githubusercontent.com/16065331/202831081-9b7bb838-78e2-43f4-b5c0-e79bcc63a780.jpg)

**Comment by RyensX** [comment]
试试最新的测试版

**Comment by smarttommyau** [comment]
解决了，麻烦了，谢谢。

**Comment by RyensX** [comment]
> 解决了，麻烦了，谢谢。

嗯，有问题可以继续反馈。其实这个bug已经出现挺久只是我一直没法复现又缺少log才拖到现在😂
