### ISSUE TITLE
收藏排列有问题

### ISSUE THREAD

**Issue by smarttommyau** [RyensX/MediaBox#67]
https://user-images.githubusercontent.com/75346987/210241276-a9c205bd-2990-4968-997a-c49849618c93.mp4

排列变成了第一格是空的，而不是最后的那个

**Comment by RyensX** [comment]
这个发新版时也偶尔遇见了，暂时还没去排查复现。你这边有没有复现步骤？

**Comment by RyensX** [comment]
简单排查了一下，这两天会发一下测试版

**Comment by RyensX** [comment]
试试最新测试版，基本修复了
