### ISSUE TITLE
弹幕加载错误：Chain validation failed

### ISSUE THREAD

**Issue by smarttommyau** [RyensX/MediaBox#74]
开什么视频都会弹这个东西，然后弹幕也不能加载。是app的问题还是接口死掉了？

**Comment by RyensX** [comment]
弹幕接口问题，还在等弹幕系统开发者回复
https://github.com/RyensX/MediaBox/issues/51#issuecomment-1403031611

**Comment by smarttommyau** [comment]
接口好像复活了😂

**Comment by RyensX** [comment]
看了一下，证书续了三个月
