### ISSUE TITLE
樱花动漫2失效

### ISSUE THREAD

**Issue by LSGLSH** [RyensX/MediaBox#85]
樱花动漫2失效了，进入不了，考虑到应该是香港或者台湾那边的网站，我分别开了代理和不开进去都是报错 #
![Screenshot_2023-05-24-23-47-35-985_com su mediabox debug](https://github.com/RyensX/MediaBox/assets/106002475/4d781d45-51b4-44a4-81fb-536301a43682)

**Comment by RyensX** [comment]
这个已经知道了，网站挂了，打算等几天看看情况，之前它也有这样诈尸的

**Comment by LSGLSH** [comment]
> 如果没救了再出一个新插件就好了

收到

**Comment by RyensX** [comment]
另外全新版本【开源视频】正在开发中，到时候体验会更好
