### ISSUE TITLE
点击樱花进入后

### ISSUE THREAD

**Issue by Bin624** [RyensX/MediaBox#9]
CrashInfo:
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Lcom/su/mediabox/pluginapi/been/AnimeEpisodeDataBean;Lcom/su/mediabox/pluginapi/been/AnimeAreaBean;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Lcom/su/mediabox/pluginapi/been/AnimeInfoBean;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/su/mediabox/pluginapi/been/AnimeCoverBean; or its super classes (declaration of 'com.su.mediabox.pluginapi.been.AnimeCoverBean' appears in base.apk)
	at com.su.mediabox.plugin.ParseHtmlUtil.parseHeroWrap(ParseHtmlUtil.kt:44)
	at com.su.mediabox.plugin.ParseHtmlUtil.parseHeroWrap$default(ParseHtmlUtil.kt:17)
	at com.su.mediabox.plugin.CustomAnimeShowModel.getAnimeShowData(CustomAnimeShowModel.kt:31)
	at com.su.mediabox.viewmodel.AnimeShowViewModel$getAnimeShowData$1.invokeSusp

**Comment by RyensX** [comment]
请升级插件
https://github.com/RyensX/SakuraAnimePlugin/releases/tag/1.1(2)
