### ISSUE TITLE
请问字幕是从那个平台拉过来的呢？

### ISSUE THREAD

**Issue by grdiv** [RyensX/MediaBox#91]
rt，以及一个需求：播放时自动横屏全屏播放，按返回键就自动退出播放了，可否提供一个一般竖屏播放的功能，下方为视频详情。

**Comment by RyensX** [comment]
1. 你指的是字幕还是弹幕？
2. 这个其实现在它是支持竖屏播放的，而且插件系统也支持插件控制横竖屏，但是播放页是独立的，所以暂时还不支持和其他数据一起显示，支持有尝试做过支持，但是还没做好。不过新的开源视频会优先支持

**Comment by grdiv** [comment]
1.想说弹幕来着，顺便问下字幕有简体吗？
2.了解。

**Comment by RyensX** [comment]
> 1.想说弹幕来着，顺便问下字幕有简体吗？
> 2.了解。

弹幕是和别的开发者合作的，具体见
https://github.com/MaybeQHL/my_danmu_pub

至于字幕，目前你看到的都只是资源内嵌的，媒体盒子还没正式做字幕支持

**Comment by grdiv** [comment]
明白，谢谢解答。
