### ISSUE TITLE
聚合搜索bug

### ISSUE THREAD

**Issue by SpaceThing** [RyensX/MediaBox#94]
页面显示错位，重启软件后再次搜索仍然错位
![Screenshot_2023-07-17-22-12-10-515_com su mediabox](https://github.com/RyensX/MediaBox/assets/61451659/696c8f8d-2756-4c3b-be80-0e54ec404de0)
![Screenshot_2023-07-17-22-12-15-891_com su mediabox](https://github.com/RyensX/MediaBox/assets/61451659/29888631-fe32-4348-be72-b5b5f737d4d2)

搜索未完成时无法点击清除按钮，或修改关键词打断搜索
录屏如下
https://github.com/RyensX/MediaBox/assets/61451659/01b61851-0226-49f0-94a3-a26a285a342e

**Comment by feiyeyuanye** [comment]
插件包含 LIBVIO 么，可能是它引起的

**Comment by RyensX** [comment]
这个问题是因为插件提供了不规则的搜索结果，可以先关闭LIBVIO解决，后面我再限制一下

**Comment by SpaceThing** [comment]
> 这个问题是因为插件提供了不规则的搜索结果，可以先关闭LIBVIO解决，后面我再限制一下

插件包括LIBVIO，更新插件后界面显示正常了
